# Generated by Django 6.1 on 2026-09-05 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField()),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('URL', models.URLField()),
                ('skills', models.ManyToManyField(db_table='vacancies_skills_map', related_name='vacancies', to='vacancies.skill')),
            ],
            options={
                'db_table': 'vacancies',
            },
        ),
    ]
