# Generated by Django 6.1 on 2026-10-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(blank=True, db_table='vacancies_skills_map', related_name='vacancies', to='vacancies.skill'),
        ),
    ]
